name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.2']
        phpunit-versions: ['latest']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.2'
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL DATABASE: test
          MYSQL_HOST: 127.0.0.1
          MYSOL_USER: admin
          MYSQL_PASSWORD: admin123
          MYSQL_ROOT_PASSWORD: admin123
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.2'
      - name: Update Composer
        run: sudo composer self-update 1.10.15 --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: run tests
        run: vendor/bin/phpunit
